# Generated by Django 4.2.4 on 2023-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
